"""
Aevum Demo — FastAPI application.

Public routes:
  GET  /              React SPA (served from dist/ via StaticFiles)
  GET  /docs          Swagger UI
  GET  /redoc         Redoc
  GET  /scalar        Scalar API explorer (interactive demo flow)
  GET  /openapi.json  OpenAPI schema (generated by FastAPI)
  GET  /health        Health check — no auth, no rate limit

Demo routes (all require X-Demo-Actor header):
  POST /demo/ingest
  POST /demo/query
  POST /demo/commit
  GET  /demo/replay/{audit_id}
  POST /demo/review/create
  GET  /demo/review/{audit_id}
  POST /demo/review/{audit_id}/approve
  POST /demo/review/{audit_id}/veto
  POST /demo/grant
  POST /demo/reset
  GET  /demo/ledger

Sandbox routes (no auth — 4-step governed demo):
  POST /sandbox/scan
  POST /sandbox/consent
  POST /sandbox/execute
  GET  /sandbox/sigchain

Security:
  - All POST bodies validated by strict Pydantic models
  - Request size capped at 32 KB
  - X-Demo-Actor restricted to known actors
  - Subjects and purposes restricted to demo values
  - Security headers on every response
  - Session cookie: HttpOnly, SameSite=lax, Secure in production
  - Rate limiting via slowapi (per-IP)
  - Max 200 concurrent sessions
  - CORSMiddleware with explicit origins (never wildcard with credentials)
"""

import asyncio
import os
import time
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager, suppress
from pathlib import Path
from typing import Annotated, Any, Literal
from uuid import uuid4

from aevum.core import Engine
from aevum.core.consent.models import ConsentGrant
from aevum.store.oxigraph import OxigraphStore
from fastapi import Body, FastAPI, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.utils import get_openapi
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, ConfigDict, Field
from sandbox_models import (
    ConsentRequest,
    ConsentResult,
    ExecuteRequest,
    ExecuteResult,
    ScanRequest,
    ScanResult,
    SigchainEntry,
    SigchainResult,
)
from sandbox_state import get_sandbox
from scalar_fastapi import get_scalar_api_reference
from seed import seed_engine
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address
from starlette.middleware.base import BaseHTTPMiddleware

# ── Constants ─────────────────────────────────────────────────────────────────

_SESSION_COOKIE = "aevum_demo"
_SESSION_TTL    = 1800        # 30 minutes
_SESSION_CAP    = 200
_IS_PRODUCTION  = bool(os.getenv("HF_SPACE_ID"))  # set by HF Spaces runtime

_ALLOWED_ACTORS = frozenset({
    "demo-agent",
    "intruder-agent",
    "demo-human",
})

_DEMO_ORIGINS = [
    "https://demo.aevum.build",
    "https://aevum-demo.fly.dev",
    "http://localhost:5173",    # Vite dev server
    "http://localhost:3000",    # Alternative dev port
    "http://localhost:7860",    # Local preview
]

_SANDBOX_TAGS = [
    {
        "name": "1. Scan",
        "description": (
            "Trigger a governed diagnostic scan. Aevum runs the request "
            "through all five barriers before any action is taken."
        ),
    },
    {
        "name": "2. Consent",
        "description": (
            "Approve or deny the proposed remediation. The consent token "
            "is cryptographically bound to this specific action."
        ),
    },
    {
        "name": "3. Execute",
        "description": (
            "Run the approved task under the Aevum kernel. Every action "
            "produces a COSE_Sign1 receipt anchored to Rekor."
        ),
    },
    {
        "name": "4. Inspect Sigchain",
        "description": (
            "Read the cryptographic audit trail. Each entry carries an "
            "Ed25519 signature and a PROV-AGENT provenance record."
        ),
    },
]

# ── Session store ─────────────────────────────────────────────────────────────

# dict[session_id → (engine, last_accessed_monotonic)]
_sessions: dict[str, tuple[Engine, float]] = {}


def _make_engine() -> Engine:
    store = OxigraphStore()          # in-memory (no path= arg)
    engine = Engine(graph_store=store)
    seed_engine(engine)
    return engine


def _get_engine(sid: str) -> Engine:
    if sid in _sessions:
        engine, _ = _sessions[sid]
        _sessions[sid] = (engine, time.monotonic())
        return engine
    if len(_sessions) >= _SESSION_CAP:
        oldest = min(_sessions, key=lambda k: _sessions[k][1])
        _sessions.pop(oldest, None)
    engine = _make_engine()
    _sessions[sid] = (engine, time.monotonic())
    return engine


def _resolve(request: Request, response: Response) -> Engine:
    sid = request.cookies.get(_SESSION_COOKIE)
    if not sid or sid not in _sessions:
        sid = str(uuid4())
        response.set_cookie(
            _SESSION_COOKIE, sid,
            max_age=_SESSION_TTL,
            samesite="lax",
            httponly=True,
            secure=_IS_PRODUCTION,
        )
    return _get_engine(sid)


def _actor(request: Request) -> str:
    raw = request.headers.get("X-Demo-Actor", "demo-agent").strip()
    return raw if raw in _ALLOWED_ACTORS else "demo-agent"


def _dump(result: Any) -> dict:
    return result.model_dump() if hasattr(result, "model_dump") else dict(result)


# ── Background cleanup ────────────────────────────────────────────────────────

async def _cleanup_loop() -> None:
    while True:
        await asyncio.sleep(300)
        cutoff = time.monotonic() - _SESSION_TTL
        stale = [sid for sid, (_, t) in list(_sessions.items()) if t < cutoff]
        for sid in stale:
            _sessions.pop(sid, None)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    task = asyncio.create_task(_cleanup_loop())
    yield
    task.cancel()
    with suppress(asyncio.CancelledError):
        await task


# ── Security middleware ───────────────────────────────────────────────────────

class RequestSizeLimitMiddleware(BaseHTTPMiddleware):
    _MAX_BYTES = 32_768  # 32 KB

    async def dispatch(self, request: Request, call_next: Any) -> Any:
        if request.method in ("POST", "PUT", "PATCH"):
            cl = request.headers.get("content-length")
            if cl and int(cl) > self._MAX_BYTES:
                return JSONResponse(
                    status_code=413,
                    content={
                        "error": "request_too_large",
                        "max_bytes": self._MAX_BYTES,
                        "detail": "Demo request bodies must be under 32 KB.",
                    },
                )
            # Also enforce when Content-Length is absent (chunked/piped transfers)
            if not cl:
                body = await request.body()
                if len(body) > self._MAX_BYTES:
                    return JSONResponse(
                        status_code=413,
                        content={
                            "error": "request_too_large",
                            "max_bytes": self._MAX_BYTES,
                            "detail": "Demo request bodies must be under 32 KB.",
                        },
                    )
        return await call_next(request)


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: Any) -> Any:
        response = await call_next(request)
        response.headers["X-Robots-Tag"] = "noindex, nofollow"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "SAMEORIGIN"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
            "style-src 'self' 'unsafe-inline'; "
            "img-src 'self' data: https://fastapi.tiangolo.com; "
            "connect-src 'self'; "
            "frame-src 'self';"
        )
        if _IS_PRODUCTION:
            response.headers["Strict-Transport-Security"] = (
                "max-age=31536000; includeSubDomains"
            )
        return response


# ── App ───────────────────────────────────────────────────────────────────────

limiter = Limiter(key_func=get_remote_address)

app = FastAPI(
    title="Aevum Demo API",
    description=(
        "Explore the five Aevum functions through three guided scenarios.\n\n"
        "Set **X-Demo-Actor** to one of: `demo-agent`, `intruder-agent`, `demo-human`.\n\n"
        "**Scenario A — Replay Proof:** `ingest` → `commit` → `replay`\n\n"
        "**Scenario B — Consent Barrier:** `query` (ok) → `query` as intruder (blocked) "
        "→ `grant` → `query` (ok)\n\n"
        "**Scenario C — GOVERN Gate:** `review/create` → `review/{id}` (pending) "
        "→ `review/{id}/approve` or `review/{id}/veto`"
    ),
    version="0.1.0-demo",
    openapi_tags=_SANDBOX_TAGS,
    lifespan=lifespan,
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(RequestSizeLimitMiddleware)
# CORSMiddleware added last = outermost = first to handle OPTIONS preflight
# Never combine allow_credentials=True with allow_origins=["*"] — browser rejects it
app.add_middleware(
    CORSMiddleware,
    allow_origins=_DEMO_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["X-Sigchain-Head", "X-Request-ID", "X-Sandbox-Session"],
)


@app.exception_handler(Exception)
async def _safe_500(request: Request, exc: Exception) -> JSONResponse:
    # Never expose tracebacks or internal details to clients.
    return JSONResponse(
        status_code=500,
        content={"error": "internal_error", "detail": "Something went wrong."},
    )


# ── Pydantic request models ───────────────────────────────────────────────────

class DemoProvenance(BaseModel):
    model_config = ConfigDict(frozen=True, extra="ignore")
    source_id: Annotated[str, Field(max_length=100)]
    chain_of_custody: Annotated[list[str], Field(min_length=1, max_length=5)]
    classification: Literal[0, 1]


class DemoIngestRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    data: Annotated[
        dict[str, str | int | float | bool | None],
        Field(max_length=20, description="Key-value payload; max 20 keys"),
    ]
    provenance: DemoProvenance
    purpose: Literal["billing-inquiry", "compliance-audit"]
    subject_id: Literal["user-demo"]


class DemoQueryRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    purpose: Literal["billing-inquiry", "compliance-audit"]
    subject_ids: Annotated[
        list[Literal["user-demo"]],
        Field(min_length=1, max_length=1),
    ]
    classification_max: Literal[0, 1] = 1
    constraints: dict[str, str] | None = None


class DemoCommitRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    event_type: Annotated[
        str,
        Field(
            pattern=r"^demo\.[a-z][a-z0-9._-]{0,98}$",
            description="Must start with 'demo.' e.g. demo.payment.approved",
        ),
    ]
    payload: Annotated[
        dict[str, str | int | float | bool | None],
        Field(max_length=20),
    ]


class DemoReviewCreateRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    proposed_action: Annotated[str, Field(min_length=1, max_length=200)]
    reason: Annotated[str, Field(min_length=1, max_length=200)]
    autonomy_level: Annotated[int, Field(ge=1, le=5)] = 3
    risk_assessment: Annotated[str, Field(max_length=200)] = ""


class DemoGrantRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    subject_id: Literal["user-demo"]
    grantee_id: Literal["demo-agent", "intruder-agent", "demo-human"]
    operations: Annotated[
        list[Literal["ingest", "query", "replay", "export"]],
        Field(min_length=1, max_length=4),
    ]
    purpose: Literal["billing-inquiry", "compliance-audit"]
    classification_max: Literal[0, 1] = 1


# ── Demo routes (hidden from Scalar via include_in_schema=False) ───────────────
# Option A chosen over sub-app mount: sub-app mount breaks middleware inheritance
# (SecurityHeadersMiddleware and RequestSizeLimitMiddleware would not apply).
# include_in_schema=False keeps all 11 routes accessible but out of the Scalar UI.

@app.post(
    "/demo/ingest",
    include_in_schema=False,
    summary="ingest — RELATE",
    description=(
        "Write data through the governed membrane into the knowledge graph. "
        "Checks Barrier 1 (Crisis), Barrier 3 (Consent), Barrier 5 (Provenance). "
        "Returns an OutputEnvelope with a signed `audit_id`."
    ),
    tags=["Scenario A – Replay Proof", "Scenario B – Consent Barrier"],
)
@limiter.limit("15/minute")
async def demo_ingest(
    body: DemoIngestRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.ingest(
        data=body.data,
        provenance=body.provenance.model_dump(),
        purpose=body.purpose,
        subject_id=body.subject_id,
        actor=_actor(request),
    )
    return _dump(result)


@app.post(
    "/demo/query",
    include_in_schema=False,
    summary="query — NAVIGATE",
    description=(
        "Traverse the knowledge graph for a declared purpose. "
        "Checks Barrier 2 (Classification Ceiling) and Barrier 3 (Consent). "
        "Use `intruder-agent` as the actor to observe Barrier 3 blocking."
    ),
    tags=["Scenario A – Replay Proof", "Scenario B – Consent Barrier"],
)
@limiter.limit("15/minute")
async def demo_query(
    body: DemoQueryRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.query(
        purpose=body.purpose,
        subject_ids=list(body.subject_ids),
        actor=_actor(request),
        constraints=body.constraints,
        classification_max=body.classification_max,
    )
    return _dump(result)


@app.post(
    "/demo/commit",
    include_in_schema=False,
    summary="commit — REMEMBER",
    description=(
        "Append a named business event to the episodic ledger. "
        "Commit does not check Consent (Barrier 3) — it records outcomes "
        "of already-governed operations. `event_type` must start with `demo.`"
    ),
    tags=["Scenario A – Replay Proof"],
)
@limiter.limit("15/minute")
async def demo_commit(
    body: DemoCommitRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.commit(
        event_type=body.event_type,
        payload=body.payload,
        actor=_actor(request),
    )
    return _dump(result)


@app.get(
    "/demo/replay/{audit_id}",
    include_in_schema=False,
    summary="replay — REPLAY",
    description=(
        "Reconstruct any past decision exactly as it occurred. "
        "Provide the `audit_id` from a previous `commit` response. "
        "The same `audit_id` always returns the same payload — "
        "this is the deterministic replay guarantee."
    ),
    tags=["Scenario A – Replay Proof"],
)
@limiter.limit("60/minute")
async def demo_replay(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.replay(audit_id=audit_id, actor=_actor(request))
    return _dump(result)


@app.post(
    "/demo/review/create",
    include_in_schema=False,
    summary="review — Create a GOVERN gate",
    description=(
        "Create a human review gate. Returns a `review_id` "
        "(`urn:aevum:audit:...`). Pass this ID to `GET /demo/review/{review_id}` "
        "to poll its status, then approve or veto it. "
        "In production systems, review gates are created by the autonomy "
        "enforcement complication (L1-L4 agents) or explicitly by the agent."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("10/minute")
async def demo_review_create(
    body: DemoReviewCreateRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    review_id = engine.create_review(
        proposed_action=body.proposed_action,
        reason=body.reason,
        actor=_actor(request),
        autonomy_level=body.autonomy_level,
        risk_assessment=body.risk_assessment,
    )
    return {
        "review_id": review_id,
        "status": "pending_review",
        "note": (
            "Poll GET /demo/review/{review_id} to see the gate. "
            "Then approve or veto it."
        ),
    }


@app.get(
    "/demo/review/{audit_id}",
    include_in_schema=False,
    summary="review — Poll a GOVERN gate",
    description=(
        "Poll the status of a pending review gate. "
        "Returns `status: pending_review` while no decision has been made. "
        "Default is veto: if the deadline passes with no decision, "
        "the operation is automatically blocked."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("60/minute")
async def demo_review_poll(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.review(audit_id=audit_id, actor=_actor(request))
    return _dump(result)


@app.post(
    "/demo/review/{audit_id}/approve",
    include_in_schema=False,
    summary="review — Approve (human decision)",
    description=(
        "Record human approval of a pending review gate. "
        "Use actor `demo-human`. Returns `status: ok`. "
        "The approval is recorded in the episodic ledger alongside the original action."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("10/minute")
async def demo_review_approve(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.review(audit_id=audit_id, actor="demo-human", action="approve")
    return _dump(result)


@app.post(
    "/demo/review/{audit_id}/veto",
    include_in_schema=False,
    summary="review — Veto (human decision)",
    description=(
        "Record human veto of a pending review gate. "
        "Use actor `demo-human`. Returns `status: error`. "
        "The veto is recorded in the sigchain. The agent cannot retry "
        "without a new review gate."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("10/minute")
async def demo_review_veto(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.review(audit_id=audit_id, actor="demo-human", action="veto")
    return _dump(result)


@app.post(
    "/demo/grant",
    include_in_schema=False,
    summary="Add a consent grant",
    description=(
        "Grant consent for an actor to perform operations on `user-demo`. "
        "Use this in Scenario B step 3 to grant `intruder-agent` access, "
        "then re-run the query to observe the barrier lift."
    ),
    tags=["Scenario B – Consent Barrier"],
)
@limiter.limit("5/minute")
async def demo_grant(
    body: DemoGrantRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    grant = ConsentGrant(
        grant_id=str(uuid4()),
        subject_id=body.subject_id,
        grantee_id=body.grantee_id,
        operations=list(body.operations),
        purpose=body.purpose,
        classification_max=body.classification_max,
        granted_at="2026-01-01T00:00:00Z",
        expires_at="2030-01-01T00:00:00Z",
    )
    engine.add_consent_grant(grant)
    return {
        "granted": True,
        "grant_id": grant.grant_id,
        "grantee_id": grant.grantee_id,
        "subject_id": grant.subject_id,
        "operations": list(body.operations),
    }


@app.post(
    "/demo/reset",
    include_in_schema=False,
    summary="Reset session",
    description=(
        "Wipe and re-seed your session. Clears all ledger entries, "
        "consent grants, and review gates. Returns you to the seeded state."
    ),
    tags=["Utilities"],
)
@limiter.limit("3/minute")
async def demo_reset(request: Request, response: Response) -> dict:
    sid = request.cookies.get(_SESSION_COOKIE)
    if sid:
        _sessions.pop(sid, None)
    _resolve(request, response)  # creates fresh session
    return {"reset": True, "message": "Session cleared and re-seeded."}


@app.get(
    "/demo/ledger",
    include_in_schema=False,
    summary="View the sigchain",
    description=(
        "Return all episodic ledger entries for your session in order. "
        "Every call to any of the five functions writes an entry. "
        "The chain grows as you run the scenarios."
    ),
    tags=["Utilities"],
)
@limiter.limit("60/minute")
async def demo_ledger(request: Request, response: Response) -> dict:
    engine = _resolve(request, response)
    entries = engine.get_ledger_entries()
    return {"count": len(entries), "entries": entries}


# ── Sandbox routes ────────────────────────────────────────────────────────────

@app.post(
    "/sandbox/scan",
    tags=["1. Scan"],
    summary="Trigger a governed diagnostic scan",
    description=(
        "Runs a diagnostic scan against the specified host. "
        "Aevum evaluates all five barriers before the scan executes. "
        "Returns a task ID and finding. Use the task ID for consent and execution."
    ),
    response_model=ScanResult,
    responses={
        200: {"description": "Scan completed, finding returned"},
        429: {"description": "Rate limit exceeded"},
    },
)
@limiter.limit("20/minute")
async def sandbox_scan(
    payload: Annotated[
        ScanRequest,
        Body(
            openapi_examples={
                "disk_full": {
                    "summary": "Disk-full on host-42",
                    "description": "The canonical Aevum demo: disk at 94%, log rotation proposed.",
                    "value": {"host_id": "host-42", "scan_type": "diagnostic"},
                },
                "memory_leak": {
                    "summary": "Memory leak on host-7",
                    "description": "Worker-pool memory growing 2 GB/hr. Critical severity.",
                    "value": {"host_id": "host-7", "scan_type": "memory_pressure"},
                },
                "cert_expiring": {
                    "summary": "TLS certificate expiring in 6 days",
                    "description": "Certificate renewal before expiry window.",
                    "value": {"host_id": "host-prod-01", "scan_type": "cert_check"},
                },
            }
        ),
    ],
    request: Request,
) -> ScanResult:
    sb = get_sandbox()
    task = sb.create_task(payload.host_id, payload.scan_type)
    chain = sb.sigchain()
    return ScanResult(
        task_id=task.task_id,
        host_id=task.host_id,
        finding=task.finding,
        severity=task.severity,  # type: ignore[arg-type]
        proposed_action=task.proposed_action,
        barriers_evaluated=chain[-1]["barrier_evaluations"],
        receipt_hash=chain[-1]["sigchain_entry_hash"],
    )


@app.post(
    "/sandbox/consent",
    tags=["2. Consent"],
    summary="Approve or deny the proposed remediation",
    description=(
        "The consent token returned here is cryptographically bound to "
        "this specific task and action. Passing it to /sandbox/execute "
        "proves human-in-the-loop approval without storing credentials."
    ),
    response_model=ConsentResult,
    responses={
        200: {"description": "Consent decision recorded"},
        404: {"description": "Task not found"},
    },
)
async def sandbox_consent(
    payload: Annotated[
        ConsentRequest,
        Body(
            openapi_examples={
                "approve": {
                    "summary": "Approve the proposed remediation",
                    "value": {
                        "task_id": "tsk_REPLACE_WITH_SCAN_RESULT",
                        "decision": "approve",
                    },
                },
                "deny": {
                    "summary": "Deny — escalate to senior engineer",
                    "value": {
                        "task_id": "tsk_REPLACE_WITH_SCAN_RESULT",
                        "decision": "deny",
                    },
                },
            }
        ),
    ],
) -> ConsentResult:
    try:
        task = get_sandbox().consent(payload.task_id, payload.decision)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found") from None
    return ConsentResult(
        task_id=task.task_id,
        decision=payload.decision,
        consent_token=task.consent_token or "",
        valid_for_seconds=900,
    )


@app.post(
    "/sandbox/execute",
    tags=["3. Execute"],
    summary="Execute the approved task under the Aevum kernel",
    description=(
        "Executes the remediation. Requires the consent token from step 2. "
        "Every action produces a COSE_Sign1 receipt. The sigchain head hash "
        "in the response links to the cryptographic audit trail."
    ),
    response_model=ExecuteResult,
    responses={
        200: {"description": "Task executed, receipt hash returned"},
        404: {"description": "Task not found"},
        409: {"description": "Consent required or token invalid"},
    },
)
async def sandbox_execute(
    payload: Annotated[
        ExecuteRequest,
        Body(
            openapi_examples={
                "execute_approved": {
                    "summary": "Execute an approved task",
                    "value": {
                        "task_id": "tsk_REPLACE_WITH_SCAN_RESULT",
                        "consent_token": "cst_REPLACE_WITH_CONSENT_RESULT",
                    },
                },
            }
        ),
    ],
) -> ExecuteResult:
    try:
        task = get_sandbox().execute(payload.task_id, payload.consent_token)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found") from None
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e)) from e
    chain = get_sandbox().sigchain()
    return ExecuteResult(
        task_id=task.task_id,
        outcome=f"Executed: {task.proposed_action}",
        sigchain_head=chain[-1]["sigchain_entry_hash"],
        rekor_entry="pending (dev mode)",
        receipt_hash=task.receipt_hash or "",
    )


@app.get(
    "/sandbox/sigchain",
    tags=["4. Inspect Sigchain"],
    summary="Inspect the cryptographic audit trail",
    description=(
        "Returns the complete sigchain for this sandbox session. "
        "Each entry carries an Ed25519 signature hash, barrier evaluations, "
        "and PROV-AGENT provenance fields. "
        "This is the AI black box — the forensic record of every action."
    ),
    response_model=SigchainResult,
)
async def sandbox_sigchain() -> SigchainResult:
    chain = get_sandbox().sigchain()
    head = chain[-1]["sigchain_entry_hash"] if chain else "0" * 64
    return SigchainResult(
        head_hash=head,
        entry_count=len(chain),
        entries=[SigchainEntry(**e) for e in chain],
    )


# ── Non-demo routes ───────────────────────────────────────────────────────────

@app.get("/health", include_in_schema=False)
async def health() -> dict:
    return {"status": "ok", "sessions": len(_sessions)}


@app.get("/scalar", include_in_schema=False)
async def scalar_ui() -> HTMLResponse:
    return get_scalar_api_reference(
        openapi_url=app.openapi_url,
        title="Aevum API Explorer",
        dark_mode=True,
        authentication={
            "preferredSecurityScheme": "DemoActor",
            "apiKey": {"token": "demo-agent"},
        },
    )


# ── Custom OpenAPI — adds X-Demo-Actor security scheme and sandbox tags ────────

def _build_openapi() -> dict:
    if app.openapi_schema:
        return app.openapi_schema
    schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
        tags=_SANDBOX_TAGS,
    )
    schema.setdefault("components", {})
    schema["components"]["securitySchemes"] = {
        "DemoActor": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Demo-Actor",
            "description": (
                "Identifies the acting entity. "
                "Values: `demo-agent`, `intruder-agent`, `demo-human`. "
                "Unknown values silently fall back to `demo-agent`."
            ),
        }
    }
    for path_data in schema.get("paths", {}).values():
        for operation in path_data.values():
            if isinstance(operation, dict):
                operation.setdefault("security", [{"DemoActor": []}])
    app.openapi_schema = schema
    return schema


app.openapi = _build_openapi  # type: ignore[method-assign]


# ── Static files — React SPA ─────────────────────────────────────────────────
# Must be LAST — routes above take priority; this catches everything else.
# html=True serves index.html for unmatched paths (React client-side routing).

_dist = Path(__file__).parent / "dist"
if _dist.exists():
    app.mount("/", StaticFiles(directory=str(_dist), html=True), name="static")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860)
