"""
Aevum Demo — FastAPI application.

Public routes:
  GET  /              Landing page (scenario guide)
  GET  /docs          Scalar API explorer
  GET  /openapi.json  OpenAPI schema (generated by FastAPI)
  GET  /health        Health check — no auth, no rate limit

Demo routes (all require X-Demo-Actor header):
  POST /demo/ingest
  POST /demo/query
  POST /demo/commit
  GET  /demo/replay/{audit_id}
  POST /demo/review/create
  GET  /demo/review/{audit_id}
  POST /demo/review/{audit_id}/approve
  POST /demo/review/{audit_id}/veto
  POST /demo/grant
  POST /demo/reset
  GET  /demo/ledger

Security:
  - All POST bodies validated by strict Pydantic models
  - Request size capped at 32 KB
  - X-Demo-Actor restricted to known actors
  - Subjects and purposes restricted to demo values
  - Security headers on every response
  - Session cookie: HttpOnly, SameSite=lax, Secure in production
  - Rate limiting via slowapi (per-IP)
  - Max 200 concurrent sessions
"""

import asyncio
import os
import time
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager, suppress
from typing import Annotated, Any, Literal
from uuid import uuid4

from aevum.core import Engine
from aevum.core.consent.models import ConsentGrant
from aevum.store.oxigraph import OxigraphStore
from fastapi import FastAPI, Request, Response
from fastapi.openapi.utils import get_openapi
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel, ConfigDict, Field
from seed import seed_engine
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address
from starlette.middleware.base import BaseHTTPMiddleware

# ── Constants ─────────────────────────────────────────────────────────────────

_SESSION_COOKIE = "aevum_demo"
_SESSION_TTL    = 1800        # 30 minutes
_SESSION_CAP    = 200
_IS_PRODUCTION  = bool(os.getenv("HF_SPACE_ID"))  # set by HF Spaces runtime

_ALLOWED_ACTORS = frozenset({
    "demo-agent",
    "intruder-agent",
    "demo-human",
})

# ── Session store ─────────────────────────────────────────────────────────────

# dict[session_id → (engine, last_accessed_monotonic)]
_sessions: dict[str, tuple[Engine, float]] = {}


def _make_engine() -> Engine:
    store = OxigraphStore()          # in-memory (no path= arg)
    engine = Engine(graph_store=store)
    seed_engine(engine)
    return engine


def _get_engine(sid: str) -> Engine:
    if sid in _sessions:
        engine, _ = _sessions[sid]
        _sessions[sid] = (engine, time.monotonic())
        return engine
    if len(_sessions) >= _SESSION_CAP:
        oldest = min(_sessions, key=lambda k: _sessions[k][1])
        _sessions.pop(oldest, None)
    engine = _make_engine()
    _sessions[sid] = (engine, time.monotonic())
    return engine


def _resolve(request: Request, response: Response) -> Engine:
    sid = request.cookies.get(_SESSION_COOKIE)
    if not sid or sid not in _sessions:
        sid = str(uuid4())
        response.set_cookie(
            _SESSION_COOKIE, sid,
            max_age=_SESSION_TTL,
            samesite="lax",
            httponly=True,
            secure=_IS_PRODUCTION,
        )
    return _get_engine(sid)


def _actor(request: Request) -> str:
    raw = request.headers.get("X-Demo-Actor", "demo-agent").strip()
    return raw if raw in _ALLOWED_ACTORS else "demo-agent"


def _dump(result: Any) -> dict:
    return result.model_dump() if hasattr(result, "model_dump") else dict(result)


# ── Background cleanup ────────────────────────────────────────────────────────

async def _cleanup_loop() -> None:
    while True:
        await asyncio.sleep(300)
        cutoff = time.monotonic() - _SESSION_TTL
        stale = [sid for sid, (_, t) in list(_sessions.items()) if t < cutoff]
        for sid in stale:
            _sessions.pop(sid, None)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    task = asyncio.create_task(_cleanup_loop())
    yield
    task.cancel()
    with suppress(asyncio.CancelledError):
        await task


# ── Security middleware ───────────────────────────────────────────────────────

class RequestSizeLimitMiddleware(BaseHTTPMiddleware):
    _MAX_BYTES = 32_768  # 32 KB

    async def dispatch(self, request: Request, call_next: Any) -> Any:
        if request.method in ("POST", "PUT", "PATCH"):
            cl = request.headers.get("content-length")
            if cl and int(cl) > self._MAX_BYTES:
                return JSONResponse(
                    status_code=413,
                    content={
                        "error": "request_too_large",
                        "max_bytes": self._MAX_BYTES,
                        "detail": "Demo request bodies must be under 32 KB.",
                    },
                )
            # Also enforce when Content-Length is absent (chunked/piped transfers)
            if not cl:
                body = await request.body()
                if len(body) > self._MAX_BYTES:
                    return JSONResponse(
                        status_code=413,
                        content={
                            "error": "request_too_large",
                            "max_bytes": self._MAX_BYTES,
                            "detail": "Demo request bodies must be under 32 KB.",
                        },
                    )
        return await call_next(request)


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: Any) -> Any:
        response = await call_next(request)
        response.headers["X-Robots-Tag"] = "noindex, nofollow"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "SAMEORIGIN"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
            "style-src 'self' 'unsafe-inline'; "
            "img-src 'self' data:; "
            "connect-src 'self'; "
            "frame-src 'self';"
        )
        if _IS_PRODUCTION:
            response.headers["Strict-Transport-Security"] = (
                "max-age=31536000; includeSubDomains"
            )
        return response


# ── App ───────────────────────────────────────────────────────────────────────

limiter = Limiter(key_func=get_remote_address)

app = FastAPI(
    title="Aevum Demo API",
    description=(
        "Explore the five Aevum functions through three guided scenarios.\n\n"
        "Set **X-Demo-Actor** to one of: `demo-agent`, `intruder-agent`, `demo-human`.\n\n"
        "**Scenario A — Replay Proof:** `ingest` → `commit` → `replay`\n\n"
        "**Scenario B — Consent Barrier:** `query` (ok) → `query` as intruder (blocked) "
        "→ `grant` → `query` (ok)\n\n"
        "**Scenario C — GOVERN Gate:** `review/create` → `review/{id}` (pending) "
        "→ `review/{id}/approve` or `review/{id}/veto`"
    ),
    version="0.1.0-demo",
    docs_url=None,     # Scalar served at /docs instead
    redoc_url=None,
    lifespan=lifespan,
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(RequestSizeLimitMiddleware)


@app.exception_handler(Exception)
async def _safe_500(request: Request, exc: Exception) -> JSONResponse:
    # Never expose tracebacks or internal details to clients.
    return JSONResponse(
        status_code=500,
        content={"error": "internal_error", "detail": "Something went wrong."},
    )


# ── Pydantic request models ───────────────────────────────────────────────────

class DemoProvenance(BaseModel):
    model_config = ConfigDict(frozen=True, extra="ignore")
    source_id: Annotated[str, Field(max_length=100)]
    chain_of_custody: Annotated[list[str], Field(min_length=1, max_length=5)]
    classification: Literal[0, 1]


class DemoIngestRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    data: Annotated[
        dict[str, str | int | float | bool | None],
        Field(max_length=20, description="Key-value payload; max 20 keys"),
    ]
    provenance: DemoProvenance
    purpose: Literal["billing-inquiry", "compliance-audit"]
    subject_id: Literal["user-demo"]


class DemoQueryRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    purpose: Literal["billing-inquiry", "compliance-audit"]
    subject_ids: Annotated[
        list[Literal["user-demo"]],
        Field(min_length=1, max_length=1),
    ]
    classification_max: Literal[0, 1] = 1
    constraints: dict[str, str] | None = None


class DemoCommitRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    event_type: Annotated[
        str,
        Field(
            pattern=r"^demo\.[a-z][a-z0-9._-]{0,98}$",
            description="Must start with 'demo.' e.g. demo.payment.approved",
        ),
    ]
    payload: Annotated[
        dict[str, str | int | float | bool | None],
        Field(max_length=20),
    ]


class DemoReviewCreateRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    proposed_action: Annotated[str, Field(min_length=1, max_length=200)]
    reason: Annotated[str, Field(min_length=1, max_length=200)]
    autonomy_level: Annotated[int, Field(ge=1, le=5)] = 3
    risk_assessment: Annotated[str, Field(max_length=200)] = ""


class DemoGrantRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    subject_id: Literal["user-demo"]
    grantee_id: Literal["demo-agent", "intruder-agent", "demo-human"]
    operations: Annotated[
        list[Literal["ingest", "query", "replay", "export"]],
        Field(min_length=1, max_length=4),
    ]
    purpose: Literal["billing-inquiry", "compliance-audit"]
    classification_max: Literal[0, 1] = 1


# ── Demo routes ───────────────────────────────────────────────────────────────

@app.post(
    "/demo/ingest",
    summary="ingest — RELATE",
    description=(
        "Write data through the governed membrane into the knowledge graph. "
        "Checks Barrier 1 (Crisis), Barrier 3 (Consent), Barrier 5 (Provenance). "
        "Returns an OutputEnvelope with a signed `audit_id`."
    ),
    tags=["Scenario A – Replay Proof", "Scenario B – Consent Barrier"],
)
@limiter.limit("15/minute")
async def demo_ingest(
    body: DemoIngestRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.ingest(
        data=body.data,
        provenance=body.provenance.model_dump(),
        purpose=body.purpose,
        subject_id=body.subject_id,
        actor=_actor(request),
    )
    return _dump(result)


@app.post(
    "/demo/query",
    summary="query — NAVIGATE",
    description=(
        "Traverse the knowledge graph for a declared purpose. "
        "Checks Barrier 2 (Classification Ceiling) and Barrier 3 (Consent). "
        "Use `intruder-agent` as the actor to observe Barrier 3 blocking."
    ),
    tags=["Scenario A – Replay Proof", "Scenario B – Consent Barrier"],
)
@limiter.limit("15/minute")
async def demo_query(
    body: DemoQueryRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.query(
        purpose=body.purpose,
        subject_ids=list(body.subject_ids),
        actor=_actor(request),
        constraints=body.constraints,
        classification_max=body.classification_max,
    )
    return _dump(result)


@app.post(
    "/demo/commit",
    summary="commit — REMEMBER",
    description=(
        "Append a named business event to the episodic ledger. "
        "Commit does not check Consent (Barrier 3) — it records outcomes "
        "of already-governed operations. `event_type` must start with `demo.`"
    ),
    tags=["Scenario A – Replay Proof"],
)
@limiter.limit("15/minute")
async def demo_commit(
    body: DemoCommitRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.commit(
        event_type=body.event_type,
        payload=body.payload,
        actor=_actor(request),
    )
    return _dump(result)


@app.get(
    "/demo/replay/{audit_id}",
    summary="replay — REPLAY",
    description=(
        "Reconstruct any past decision exactly as it occurred. "
        "Provide the `audit_id` from a previous `commit` response. "
        "The same `audit_id` always returns the same payload — "
        "this is the deterministic replay guarantee."
    ),
    tags=["Scenario A – Replay Proof"],
)
@limiter.limit("60/minute")
async def demo_replay(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.replay(audit_id=audit_id, actor=_actor(request))
    return _dump(result)


@app.post(
    "/demo/review/create",
    summary="review — Create a GOVERN gate",
    description=(
        "Create a human review gate. Returns a `review_id` "
        "(`urn:aevum:audit:...`). Pass this ID to `GET /demo/review/{review_id}` "
        "to poll its status, then approve or veto it. "
        "In production systems, review gates are created by the autonomy "
        "enforcement complication (L1-L4 agents) or explicitly by the agent."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("10/minute")
async def demo_review_create(
    body: DemoReviewCreateRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    review_id = engine.create_review(
        proposed_action=body.proposed_action,
        reason=body.reason,
        actor=_actor(request),
        autonomy_level=body.autonomy_level,
        risk_assessment=body.risk_assessment,
    )
    return {
        "review_id": review_id,
        "status": "pending_review",
        "note": (
            "Poll GET /demo/review/{review_id} to see the gate. "
            "Then approve or veto it."
        ),
    }


@app.get(
    "/demo/review/{audit_id}",
    summary="review — Poll a GOVERN gate",
    description=(
        "Poll the status of a pending review gate. "
        "Returns `status: pending_review` while no decision has been made. "
        "Default is veto: if the deadline passes with no decision, "
        "the operation is automatically blocked."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("60/minute")
async def demo_review_poll(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.review(audit_id=audit_id, actor=_actor(request))
    return _dump(result)


@app.post(
    "/demo/review/{audit_id}/approve",
    summary="review — Approve (human decision)",
    description=(
        "Record human approval of a pending review gate. "
        "Use actor `demo-human`. Returns `status: ok`. "
        "The approval is recorded in the episodic ledger alongside the original action."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("10/minute")
async def demo_review_approve(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.review(audit_id=audit_id, actor="demo-human", action="approve")
    return _dump(result)


@app.post(
    "/demo/review/{audit_id}/veto",
    summary="review — Veto (human decision)",
    description=(
        "Record human veto of a pending review gate. "
        "Use actor `demo-human`. Returns `status: error`. "
        "The veto is recorded in the sigchain. The agent cannot retry "
        "without a new review gate."
    ),
    tags=["Scenario C – GOVERN Gate"],
)
@limiter.limit("10/minute")
async def demo_review_veto(
    audit_id: str, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    result = engine.review(audit_id=audit_id, actor="demo-human", action="veto")
    return _dump(result)


@app.post(
    "/demo/grant",
    summary="Add a consent grant",
    description=(
        "Grant consent for an actor to perform operations on `user-demo`. "
        "Use this in Scenario B step 3 to grant `intruder-agent` access, "
        "then re-run the query to observe the barrier lift."
    ),
    tags=["Scenario B – Consent Barrier"],
)
@limiter.limit("5/minute")
async def demo_grant(
    body: DemoGrantRequest, request: Request, response: Response
) -> dict:
    engine = _resolve(request, response)
    grant = ConsentGrant(
        grant_id=str(uuid4()),
        subject_id=body.subject_id,
        grantee_id=body.grantee_id,
        operations=list(body.operations),
        purpose=body.purpose,
        classification_max=body.classification_max,
        granted_at="2026-01-01T00:00:00Z",
        expires_at="2030-01-01T00:00:00Z",
    )
    engine.add_consent_grant(grant)
    return {
        "granted": True,
        "grant_id": grant.grant_id,
        "grantee_id": grant.grantee_id,
        "subject_id": grant.subject_id,
        "operations": list(body.operations),
    }


@app.post(
    "/demo/reset",
    summary="Reset session",
    description=(
        "Wipe and re-seed your session. Clears all ledger entries, "
        "consent grants, and review gates. Returns you to the seeded state."
    ),
    tags=["Utilities"],
)
@limiter.limit("3/minute")
async def demo_reset(request: Request, response: Response) -> dict:
    sid = request.cookies.get(_SESSION_COOKIE)
    if sid:
        _sessions.pop(sid, None)
    _resolve(request, response)  # creates fresh session
    return {"reset": True, "message": "Session cleared and re-seeded."}


@app.get(
    "/demo/ledger",
    summary="View the sigchain",
    description=(
        "Return all episodic ledger entries for your session in order. "
        "Every call to any of the five functions writes an entry. "
        "The chain grows as you run the scenarios."
    ),
    tags=["Utilities"],
)
@limiter.limit("60/minute")
async def demo_ledger(request: Request, response: Response) -> dict:
    engine = _resolve(request, response)
    entries = engine.get_ledger_entries()
    return {"count": len(entries), "entries": entries}


# ── Non-demo routes ───────────────────────────────────────────────────────────

@app.get("/health", include_in_schema=False)
async def health() -> dict:
    return {"status": "ok", "sessions": len(_sessions)}


@app.get("/docs", include_in_schema=False)
async def scalar_docs() -> HTMLResponse:
    return HTMLResponse(_SCALAR_HTML)


@app.get("/", include_in_schema=False)
async def landing() -> HTMLResponse:
    return HTMLResponse(_LANDING_HTML)


# ── Custom OpenAPI — adds X-Demo-Actor security scheme ────────────────────────

def _build_openapi() -> dict:
    if app.openapi_schema:
        return app.openapi_schema
    schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )
    schema.setdefault("components", {})
    schema["components"]["securitySchemes"] = {
        "DemoActor": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Demo-Actor",
            "description": (
                "Identifies the acting entity. "
                "Values: `demo-agent`, `intruder-agent`, `demo-human`. "
                "Unknown values silently fall back to `demo-agent`."
            ),
        }
    }
    for path_data in schema.get("paths", {}).values():
        for operation in path_data.values():
            if isinstance(operation, dict):
                operation.setdefault("security", [{"DemoActor": []}])
    app.openapi_schema = schema
    return schema


app.openapi = _build_openapi  # type: ignore[method-assign]


# ── HTML pages ────────────────────────────────────────────────────────────────

_SCALAR_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Aevum API Explorer</title>
</head>
<body>
  <script
    id="api-reference"
    data-url="/openapi.json">
  </script>
  <script>
    document.getElementById('api-reference').dataset.configuration = JSON.stringify({
      darkMode: true,
      layout: 'modern',
      defaultHttpClient: {targetKey: 'demo'},
      authentication: {
        preferredSecurityScheme: 'DemoActor',
        apiKey: {token: 'demo-agent'},
      },
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference@latest/dist/browser/standalone.min.js"></script>
</body>
</html>"""

_LANDING_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Aevum — Live Demo</title>
  <style>
    :root {
      --bg: #0d0d0d; --surface: #161616; --border: #2a2a2a;
      --text: #e0e0e0; --muted: #888; --accent: #a78bfa;
      --ok: #4ade80; --error: #f87171; --pending: #fbbf24;
      --mono: "SF Mono","Fira Code","Cascadia Code",monospace;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: var(--bg); color: var(--text); font-family: var(--mono);
           font-size: 13px; line-height: 1.7; padding: 24px 20px 48px; max-width: 820px;
           margin: 0 auto; }
    h1 { font-size: 20px; color: var(--accent); letter-spacing: .08em; margin-bottom: 4px; }
    .tagline { color: var(--muted); font-size: 12px; margin-bottom: 32px; }
    .open-btn {
      display: inline-block; background: var(--accent); color: #0d0d0d;
      padding: 9px 20px; font-family: var(--mono); font-size: 13px;
      font-weight: 600; text-decoration: none; margin-bottom: 40px;
    }
    .open-btn:hover { opacity: .85; }
    h2 { font-size: 13px; color: var(--accent); margin-bottom: 6px; }
    .scenario { border: 1px solid var(--border); margin-bottom: 20px; }
    .scenario-header { padding: 10px 14px; border-bottom: 1px solid var(--border);
                       background: var(--surface); }
    .scenario-label { font-size: 11px; color: var(--muted); margin-bottom: 2px; }
    .scenario-title { font-size: 13px; color: var(--text); }
    .scenario-desc { font-size: 11px; color: var(--muted); margin-top: 3px; }
    .steps { padding: 12px 14px; }
    .step { margin-bottom: 16px; }
    .step:last-child { margin-bottom: 0; }
    .step-num { font-size: 10px; color: var(--muted); margin-bottom: 4px; }
    .step-fn { color: var(--accent); font-size: 12px; }
    .step-actor { font-size: 11px; color: var(--muted); }
    .step-actor span { color: var(--text); }
    pre {
      background: #111; border: 1px solid var(--border); padding: 8px 10px;
      margin-top: 6px; font-size: 11px; overflow-x: auto;
      white-space: pre; line-height: 1.5;
    }
    .note { font-size: 11px; color: var(--muted); margin-top: 6px;
            border-left: 2px solid var(--accent); padding-left: 8px; }
    .actor-table { width: 100%; border-collapse: collapse; margin-bottom: 32px;
                   font-size: 12px; }
    .actor-table th { text-align: left; color: var(--muted); font-weight: normal;
                      padding: 4px 8px; border-bottom: 1px solid var(--border); }
    .actor-table td { padding: 5px 8px; border-bottom: 1px solid var(--border); }
    .actor-name { color: var(--accent); }
    .section-label { font-size: 10px; color: var(--muted); text-transform: uppercase;
                     letter-spacing: .1em; margin-bottom: 10px; margin-top: 32px; }
    footer { margin-top: 48px; font-size: 11px; color: var(--muted); border-top:
             1px solid var(--border); padding-top: 16px; }
    footer a { color: var(--muted); }
  </style>
</head>
<body>
<main id="main-content">

<h1>AEVUM</h1>
<p class="tagline">The governed context kernel — live playground</p>

<a class="open-btn" href="/docs" target="_blank">Open API Explorer →</a>

<p class="section-label">How to use</p>
<p style="font-size:12px; color:var(--muted); margin-bottom:16px;">
  The API Explorer (Scalar) opens in a new tab. Click <strong>Authorize</strong>
  and enter your actor name. Then follow the scenarios below — each step maps
  directly to an endpoint you can try in the explorer.
</p>

<table class="actor-table">
  <thead>
    <tr><th>Actor</th><th>Consent grants</th><th>Use in</th></tr>
  </thead>
  <tbody>
    <tr>
      <td class="actor-name">demo-agent</td>
      <td>ingest, query, replay on user-demo</td>
      <td>Scenarios A and B (step 1)</td>
    </tr>
    <tr>
      <td class="actor-name">intruder-agent</td>
      <td>None initially</td>
      <td>Scenario B (steps 2–4)</td>
    </tr>
    <tr>
      <td class="actor-name">demo-human</td>
      <td>None (review does not check consent)</td>
      <td>Scenario C (approve/veto)</td>
    </tr>
  </tbody>
</table>

<p class="section-label">Scenario A — Replay Proof</p>

<div class="scenario">
  <div class="scenario-header">
    <div class="scenario-label">Scenario A</div>
    <div class="scenario-title">Replay Proof</div>
    <div class="scenario-desc">A compliance auditor arrives. Prove your agent's decision used only consented data.</div>
  </div>
  <div class="steps">

    <div class="step">
      <div class="step-num">Step 1</div>
      <div class="step-fn">POST /demo/ingest</div>
      <div class="step-actor">Actor: <span>demo-agent</span></div>
      <pre>{
  "data": {"invoice_id": "INV-2026-001", "amount": 1500.00},
  "provenance": {
    "source_id": "billing-system",
    "chain_of_custody": ["billing-system"],
    "classification": 1
  },
  "purpose": "billing-inquiry",
  "subject_id": "user-demo"
}</pre>
      <div class="note">Response: status ok, audit_id issued and signed into the sigchain.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 2</div>
      <div class="step-fn">POST /demo/commit</div>
      <div class="step-actor">Actor: <span>demo-agent</span></div>
      <pre>{
  "event_type": "demo.payment.approved",
  "payload": {"invoice_id": "INV-2026-001", "amount": 1500.00}
}</pre>
      <div class="note">Copy the audit_id from this response. You will use it in step 3.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 3</div>
      <div class="step-fn">GET /demo/replay/{audit_id}</div>
      <div class="step-actor">Actor: <span>demo-agent</span> — paste the audit_id from step 2</div>
      <div class="note">replayed_payload is identical to the original commit payload. The same audit_id always returns the same result. This is the guarantee.</div>
    </div>

  </div>
</div>

<p class="section-label">Scenario B — Consent Barrier</p>

<div class="scenario">
  <div class="scenario-header">
    <div class="scenario-label">Scenario B</div>
    <div class="scenario-title">Consent Barrier</div>
    <div class="scenario-desc">Your agent tries to access data it was never authorized to see.</div>
  </div>
  <div class="steps">

    <div class="step">
      <div class="step-num">Step 1</div>
      <div class="step-fn">POST /demo/query</div>
      <div class="step-actor">Actor: <span>demo-agent</span></div>
      <pre>{
  "purpose": "billing-inquiry",
  "subject_ids": ["user-demo"],
  "classification_max": 1
}</pre>
      <div class="note">status: ok — consent grant exists.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 2</div>
      <div class="step-fn">POST /demo/query</div>
      <div class="step-actor">Actor: <span>intruder-agent</span> — change actor in Scalar</div>
      <pre>{
  "purpose": "billing-inquiry",
  "subject_ids": ["user-demo"],
  "classification_max": 1
}</pre>
      <div class="note">status: error — Barrier 3 fires. The data was not filtered. The operation was blocked.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 3</div>
      <div class="step-fn">POST /demo/grant</div>
      <div class="step-actor">Actor: any</div>
      <pre>{
  "subject_id": "user-demo",
  "grantee_id": "intruder-agent",
  "operations": ["query"],
  "purpose": "billing-inquiry",
  "classification_max": 1
}</pre>
    </div>

    <div class="step">
      <div class="step-num">Step 4</div>
      <div class="step-fn">POST /demo/query</div>
      <div class="step-actor">Actor: <span>intruder-agent</span> — same request as step 2</div>
      <div class="note">status: ok — consent granted. Same actor, same query, different outcome. The kernel enforced it.</div>
    </div>

  </div>
</div>

<p class="section-label">Scenario C — GOVERN Gate</p>

<div class="scenario">
  <div class="scenario-header">
    <div class="scenario-label">Scenario C</div>
    <div class="scenario-title">GOVERN Gate</div>
    <div class="scenario-desc">An autonomous agent has queued an action that requires human oversight before execution.</div>
  </div>
  <div class="steps">

    <div class="step">
      <div class="step-num">Step 1</div>
      <div class="step-fn">POST /demo/review/create</div>
      <div class="step-actor">Actor: <span>demo-agent</span></div>
      <pre>{
  "proposed_action": "Issue $15,000 credit to customer account",
  "reason": "Billing dispute resolution — amount exceeds autonomous limit",
  "autonomy_level": 3,
  "risk_assessment": "Irreversible financial transaction"
}</pre>
      <div class="note">Response includes review_id. Copy it — you will use it in steps 2 and 3.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 2</div>
      <div class="step-fn">GET /demo/review/{review_id}</div>
      <div class="step-actor">Actor: <span>demo-agent</span> — paste the review_id</div>
      <div class="note">status: pending_review, review_required: true. The veto clock is running. If the deadline passes with no decision, the operation is automatically blocked.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 3a — Approve</div>
      <div class="step-fn">POST /demo/review/{review_id}/approve</div>
      <div class="step-actor">Actor: <span>demo-human</span> — change actor in Scalar</div>
      <div class="note">status: ok. Approval recorded in the sigchain alongside the original action.</div>
    </div>

    <div class="step">
      <div class="step-num">Step 3b — Veto (alternative)</div>
      <div class="step-fn">POST /demo/review/{review_id}/veto</div>
      <div class="step-actor">Actor: <span>demo-human</span></div>
      <div class="note">status: error. Vetoed and recorded. The agent cannot retry without a new review gate.</div>
    </div>

  </div>
</div>

<p class="section-label">Utilities</p>
<p style="font-size:12px; color:var(--muted);">
  <strong>GET /demo/ledger</strong> — See every sigchain entry accumulate as you run the scenarios.<br>
  <strong>POST /demo/reset</strong> — Clear your session and return to the seeded state.
</p>

</main>
<footer>
  <p>
    <a href="https://github.com/aevum-labs/aevum">GitHub</a> ·
    <a href="https://aevum.build">aevum.build</a> ·
    Apache-2.0
  </p>
  <p style="margin-top:6px;">
    Session data is isolated per visitor and resets on container restart.
    No data leaves your browser session. No accounts required.
  </p>
</footer>

</body>
</html>"""


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860)
